// Generated by gencpp from file pacmod_msgs/HeartbeatVCU.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_HEARTBEATVCU_H
#define PACMOD_MSGS_MESSAGE_HEARTBEATVCU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pacmod_msgs
{
template <class ContainerAllocator>
struct HeartbeatVCU_
{
  typedef HeartbeatVCU_<ContainerAllocator> Type;

  HeartbeatVCU_()
    : header()
    , heartbeat_msg(0)  {
    }
  HeartbeatVCU_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , heartbeat_msg(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _heartbeat_msg_type;
  _heartbeat_msg_type heartbeat_msg;





  typedef boost::shared_ptr< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> const> ConstPtr;

}; // struct HeartbeatVCU_

typedef ::pacmod_msgs::HeartbeatVCU_<std::allocator<void> > HeartbeatVCU;

typedef boost::shared_ptr< ::pacmod_msgs::HeartbeatVCU > HeartbeatVCUPtr;
typedef boost::shared_ptr< ::pacmod_msgs::HeartbeatVCU const> HeartbeatVCUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pacmod_msgs': ['/home/mars/git/aev_autoware_bridge/src/pacmod_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "713f3573607d6d775725092ba7895338";
  }

  static const char* value(const ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x713f3573607d6d77ULL;
  static const uint64_t static_value2 = 0x5725092ba7895338ULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/HeartbeatVCU";
  }

  static const char* value(const ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint16 heartbeat_msg\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.heartbeat_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeartbeatVCU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::HeartbeatVCU_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "heartbeat_msg: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.heartbeat_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_HEARTBEATVCU_H
