// Generated by gencpp from file pacmod_msgs/PIDTuningCmdRpt.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_PIDTUNINGCMDRPT_H
#define PACMOD_MSGS_MESSAGE_PIDTUNINGCMDRPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pacmod_msgs
{
template <class ContainerAllocator>
struct PIDTuningCmdRpt_
{
  typedef PIDTuningCmdRpt_<ContainerAllocator> Type;

  PIDTuningCmdRpt_()
    : header()
    , selection(0)
    , term(0)
    , value(0.0)  {
    }
  PIDTuningCmdRpt_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , selection(0)
    , term(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _selection_type;
  _selection_type selection;

   typedef uint8_t _term_type;
  _term_type term;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> const> ConstPtr;

}; // struct PIDTuningCmdRpt_

typedef ::pacmod_msgs::PIDTuningCmdRpt_<std::allocator<void> > PIDTuningCmdRpt;

typedef boost::shared_ptr< ::pacmod_msgs::PIDTuningCmdRpt > PIDTuningCmdRptPtr;
typedef boost::shared_ptr< ::pacmod_msgs::PIDTuningCmdRpt const> PIDTuningCmdRptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pacmod_msgs': ['/home/mars/git/aev_autoware_bridge/src/pacmod_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1adb13cb5dea1ada09d72c41371cee1c";
  }

  static const char* value(const ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1adb13cb5dea1adaULL;
  static const uint64_t static_value2 = 0x09d72c41371cee1cULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/PIDTuningCmdRpt";
  }

  static const char* value(const ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8 selection  # Wheel selection to be tuned\n"
"uint8 term\n"
"float64 value			 # Use this value with specified operator on character\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.selection);
      stream.next(m.term);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDTuningCmdRpt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::PIDTuningCmdRpt_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "selection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.selection);
    s << indent << "term: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.term);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_PIDTUNINGCMDRPT_H
