// Generated by gencpp from file pacmod_msgs/VehicleSpeedCmd.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_VEHICLESPEEDCMD_H
#define PACMOD_MSGS_MESSAGE_VEHICLESPEEDCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pacmod_msgs
{
template <class ContainerAllocator>
struct VehicleSpeedCmd_
{
  typedef VehicleSpeedCmd_<ContainerAllocator> Type;

  VehicleSpeedCmd_()
    : header()
    , vehicle_speed(0.0)
    , vehicle_speed_valid(false)  {
    }
  VehicleSpeedCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicle_speed(0.0)
    , vehicle_speed_valid(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _vehicle_speed_type;
  _vehicle_speed_type vehicle_speed;

   typedef uint8_t _vehicle_speed_valid_type;
  _vehicle_speed_valid_type vehicle_speed_valid;





  typedef boost::shared_ptr< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleSpeedCmd_

typedef ::pacmod_msgs::VehicleSpeedCmd_<std::allocator<void> > VehicleSpeedCmd;

typedef boost::shared_ptr< ::pacmod_msgs::VehicleSpeedCmd > VehicleSpeedCmdPtr;
typedef boost::shared_ptr< ::pacmod_msgs::VehicleSpeedCmd const> VehicleSpeedCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pacmod_msgs': ['/home/mars/git/autoware.ai/src/aev_autoware_bridge/src/actuation/aev/pacmod_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ba1a553a705f56c5ff6f04171e49396";
  }

  static const char* value(const ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ba1a553a705f56cULL;
  static const uint64_t static_value2 = 0x5ff6f04171e49396ULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/VehicleSpeedCmd";
  }

  static const char* value(const ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 vehicle_speed         # Measured vehicle speed\n"
"bool vehicle_speed_valid      # Flag indicating if measured vehicle speed is valid    \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicle_speed);
      stream.next(m.vehicle_speed_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleSpeedCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::VehicleSpeedCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicle_speed: ";
    Printer<double>::stream(s, indent + "  ", v.vehicle_speed);
    s << indent << "vehicle_speed_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vehicle_speed_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_VEHICLESPEEDCMD_H
